### PR TITLE
Improve first rebuild experience

### PR DESCRIPTION
**Pull request by heldersepu**
Here are some of the adjustments

- No more \bin and \obj folders on git, those are generated every time we compile
- Remove the hardcoded BASS.NET, now the project uses the NuGet version
- Copy the needed dll in a PreBuildEvent to the bin folder
- Move the Bass.BASS_Init to the MainForm_Shown and if it fails we show an error message
- Add the GitIgnore for Visual Studio

### CODE REVIEW

**Comment by heldersepu** [comment]
This will fix Issue #1

**Comment by ProfessorCattington** [comment]
Oh neat! Thank you very much. I don't use git very often so I don't know
much about trimming down projects for others. I was wondering if you could
elaborate on the changes to the csproj file. I don't do many projects like
this so I don't quite understand what that change is for.

**Comment by heldersepu** [comment]
The .csproj is your project file:
https://github.com/ProfessorCattington/MP3-splitter/pull/2/files#diff-e10bbe6b59122fac74e80c3493409561

Most of those changes you see happen automatically as you add/remove references.

**Line 50**
I removed the reference to "\Program Files (x86)\BASS.NET\v4.0\Bass.Net.dll" not all developers will have that, instead that is downloaded from Nuget.
**Line 94** && **Line124**
Addition of LICENSE.rtf and readme.txt, those are part of [Bass.NetWrapper](https://www.nuget.org/packages/Bass.NetWrapper/) 
**Line 95**
Addition of packages.config that keeps all the Nuget Packages your projects is using
**PreBuildEvent**
Your project needs a native dll in the target folder (bin/debug) that automates the copy

**Comment by ProfessorCattington** [comment]
I'll have to look into what nuget is. If I have time this weekend I'll also look into your suggestion.

**Comment by heldersepu** [comment]
Let me know if you have any questions...
I guess you are not very familiar with C# and VisualStudio

**Comment by ProfessorCattington** [comment]
Ok. I will email you this weekend when I start working on it again.

**Comment by heldersepu** [comment]
Good, I started working on the a way to auto split the mp3
Will send you a pull request so you have latest...

**Pull request merged**
